SELECT * FROM CUSTOMER LIMIT 20

--Q1. What is the total revenue generated by male v5. female customers?

SELECT GENDER, SUM(PURCHASE_AMOUNT) AS revenue
from customer
group by GENDER

--Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' and purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)
--Q3. Which are the top 5 products with the highest average review rating?

SELECT item_purchased, ROUND(AVG(review_rating ::numeric), 3) as "Average Product Rating"
from customer
group by item_purchased
order by AVG (review_rating) desc
limit 5;
--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

Select Round(Avg(purchase_amount :: numeric), 2), shipping_type
from customer
where shipping_type in ('Standard', 'Express')
GROUP by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-su

select * from customer
SELECT purchase_amount, subscription_status
from customer
group by subscription_status;

SELECT subscription_status, Round(AVG(purchase_amount::numeric),2) as "average_amount", 
SUM(purchase_amount) as "total_amount", COUNT(customer_id) as "total_customer"
FROM customer
GROUP BY subscription_status
ORDER BY total_amount, average_amount DESC

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased, percent FROM customer
WHERE discount_applied ='Yes'
GROUP BY item_purchased
ORDER BY (COUNT ( SELECT subscription_status where discount_applied = 'YES')) DESC
limit 5;

SELECT item_purchased, Round(
100 * SUM( CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*), 2) AS discount_rate
from customer
GROUP BY item_purchased
ORDER BY discount_rate desc
limit 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and shOw the count of each segment.

With customer_type as (SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END as customer_segment
from customer
)
SELECT customer_segment, COUNT(*) as "Number os Customers"
from customer_type
GROUP BY customer_segment

--Q8. What are the top 3 most purchased products within each category?

with item_counts as (
select category, 
item_purchased, COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category ORDER BY COUNT(customer_id) DESC) AS item_rank --Rank and dense rank not used here , row_number used 
from customer
group by category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select * from customer
with abc as(
SELECT previous_purchases, 
Count(subscription_status = 'Yes') as Subscribers
from customer
where previous_purchases > 5)

SELECT subscription_status,
COUNT (customer_id) as repeat_buyers
from customer
where previous_purchases > 5
GROUP BY subscription_status
)

--Q10. What is the revenue contribution of each age group?

SELECT age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group 
order by total_revenue desc
